### ISSUE TITLE
[FEATURE REQUEST] Make MilkDrop 3D and Run in Virtual Reality at 360 degrees !!! (Don't know why is has not happen yet!)

### ISSUE THREAD

**Issue by ModfireH** [milkdrop2077/MilkDrop3#75]
[FEATURE REQUEST]: Make MilkDrop in 3D Running in a  360 degrees View In Virtual Reality
 (something like what https://www.plane9.com/ does,  Don't know why is has not happen yet!) it's 2024 DAMIT

Some History
In 1968 Ivan Sutherland and his student Bob Sproull created the first VR / AR head mounted display (Sword of Damocles) that was connected to a computer.
https://www.vrs.org.uk/virtual-reality/history.html#:~:text=In%201968%20Ivan%20Sutherland%20and,ceiling%20(hence%20its%20name)

MilkDrop is a hardware-accelerated music visualization plugin for Winamp and Kodi, which was originally developed by Ryan
Geiss in 2001. It uses DirectX and beat detection to render iterated images which blend seamlessly.
https://en.wikipedia.org/wiki/MilkDrop

Make MilkDrop 3D and Run in Virtual Reality at 360 degrees !!! Please :)

**Comment by milkdrop2077** [comment]
Don't wait for someone to make it, learn DirectX shaders, c++, 3D and start updating the code :)

**Comment by ModfireH** [comment]
Dude I'm to stupid to do that 😭On Jun 23, 2024 12:42 AM, milkdrop2077 ***@***.***> wrote:
Don't wait for someone to make it, learn DirectX shaders, c++, 3D and start updating the code :)

**Comment by Glitchy-Sheep** [comment]
Yeah, that would be really great. Even though I haven't any vr headset, lol.

**Comment by NikkyAI** [comment]
have done this using "some" additional software.. 
running nestdrop (VJing focused software, forked off mildrop2, more performance improvements, more stable fps, multiple decks, audio device selection.. and a lot easier to comtrol and build queues (and i can run 2+ decks while being in VRC on the same machine) multiple decks, ..... but milkdrop3 is probably good enough if you can use it entirely without the OSD coming up),
using OBS to send the visuals and music synced to the world.. (generally vrcdn is the best option, twitch will do)
and then .. pick a world that has a dome screen or a spherical screen.. if not.. build it yourself (there exist plenty already though)

you may need to use additional software to get the dome mapping right.. i recommend `fulldome vj plugin for resolume`
you may need some virtual audio device to play the music to.. which milkdrop or nestdrop can listen to.. otherwise you either hear the music twice or the visuals in world will be desynced

with low latency streaming on vrcdn the roundtrip usually only is about 200-500ms for me, but ... your experience may vary

doing VJing for friends and strangers in vrchat regularly.. 

hoping to see more people enjoy the trippy visuals all around us

**Comment by VisualBoy** [comment]
i can do it for you if needed

**Comment by ModfireH** [comment]
That's awesome, You can make it look something like https://www.plane9.com/

Do you have a VR headset?

 It's not for me it's for the world 😁 
> i can do it for you if needed

**Comment by VisualBoy** [comment]
> That's awesome, You can make it look something like https://www.plane9.com/
> 
> Do you have a VR headset?
> 
> It's not for me it's for the world 😁
> 
> > i can do it for you if needed

Sure, but not for free..  I need to pay bills

**Comment by ModfireH** [comment]
> > That's awesome, You can make it look something like https://www.plane9.com/
> > Do you have a VR headset?
> > It's not for me it's for the world 😁
> > > i can do it for you if needed
> 
> Sure, but not for free.. I need to pay bills

If I had disposable income, I would, Thanks for the offer VisualBoy!  maybe in the future......
